language: go

os:
  - linux
  - osx

env:
  - SCRIPT=test CLANG=3.9

matrix:
  include:
    - env: SCRIPT=test CLANG=3.8
      os: linux
    - env: SCRIPT=test CLANG=3.7
      os: linux
    - env: SCRIPT=test CLANG=3.6
      os: linux
    - env: SCRIPT=test CLANG=3.4
      os: linux
    - env: SCRIPT=lint CLANG=3.9
      os: linux
    - env: SCRIPT=sqlite3 CLANG=3.9
      os: osx

before_install:
  - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-add-repository "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-$CLANG main"
        sudo apt-get update
        sudo apt-cache search clang
        sudo apt-get install -f -y --force-yes clang-$CLANG lldb-$CLANG
      fi

  - |
      if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        rvm get head
      fi

  # gocovmerge is used to merge all the separate unit/integration test coverage
  # profiles.
  - go get -u github.com/wadey/gocovmerge

script:
  - . ./travis/$SCRIPT.sh

after_success:
  - include_cov=coverage.txt bash <(curl -s https://codecov.io/bash)

after_failure:
  # Print out the failures (removing a lot of the noise).
  - cat /tmp/out.txt | grep -v -- "--- PASS" | grep -v -- "=== RUN"
